// client/src/lib/components/ui/navbar/navbar.svelte
<script lang="ts">
import ThemeToggle from "$lib/components/theme-toggle.svelte";
import Package2 from "lucide-svelte/icons/package-2";
</script>

<nav
    class="flex w-full justify-between items-center border-b border-b-foreground/10 p-2 py-5 px-10 lg:px-20"
>
    <div class="flex justify-evenly items-center gap-4">
        <a
            href="##"
            class="flex items-center gap-2 text-lg font-semibold md:text-base"
        >
            <Package2 class="h-8 w-8" />
            <span class="sr-only">Konsider</span>
        </a>
        <h1 class="text-3xl font-bold">KONSIDER</h1>
    </div>
    <ThemeToggle />
</nav>

// prototype/konsider_client/src/components/ui/Navbar.tsx
import { Button } from "./Button";

export default function Navbar({ toggleModal }: { toggleModal: () => void }) {
  return (
    <nav className="border-b border-b-foreground/10 w-full h-20 flex justify-between items-center lg:px-16 md:px-14 sm:px-8 px-4 pb-5">
      <section>
        <h2 className="text-3xl uppercase font-bold">Konsider</h2>
      </section>
      <section>
        <Button variant={"default"} size={"lg"} onClick={toggleModal}>
          Create Post
        </Button>
      </section>
    </nav>
  );
}
